### ISSUE TITLE
Замечания по 3 лабе

### ISSUE THREAD

**Issue by jovfer** [AlexZimin/CPP#2]
- [x] https://github.com/AlexZimin/CPP/blob/f2a805123376036e5884c71d9f1cb6051fc7c392/Lab3/Lab3/vector.cpp#L12 можно упростить, обычно  isEmpty <=> (length == 0), естественнее смотрится
- [x] https://github.com/AlexZimin/CPP/blob/f2a805123376036e5884c71d9f1cb6051fc7c392/Lab3/Lab3/vector.cpp#L15 порядок параметров: чаще первым делают указатель, а следом длину
- [x] https://github.com/AlexZimin/CPP/blob/f2a805123376036e5884c71d9f1cb6051fc7c392/Lab3/Lab3/vector.cpp#L54 надо все-таки переименовать. У функции очень сильный побочный эффект: удаляет память по переданному указателю, это должно быть отражено в названии, по сути это перемещение
- [x] https://github.com/AlexZimin/CPP/blob/f2a805123376036e5884c71d9f1cb6051fc7c392/Lab3/Lab3/vector.cpp#L115 кажется на прошлой паре обсуждали, не надо менять индекс точно. Либо бросать исключение, либо позволять обращаться к несуществующим данным
- [x] https://github.com/AlexZimin/CPP/blob/f2a805123376036e5884c71d9f1cb6051fc7c392/Lab3/Lab3/vector.h#L22 думаю стоит убрать в приватную часть

**Comment by AlexZimin** [comment]
Спасибо за фидбек! Применил все исправления.
